### ISSUE TITLE
go get failing!

### ISSUE THREAD

**Issue by lohith-bellad** [mpiraux/master-thesis#2]
$ go get github.com/mpiraux/master-thesis                                       ✔  3737  16:32:43
# github.com/mpiraux/pigotls
In file included from ../../go/src/github.com/mpiraux/pigotls/pigotls.go:8:
./picotls/include/picotls/openssl.h:25:10: fatal error: 'openssl/opensslv.h' file not found
#include <openssl/opensslv.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by mpiraux** [comment]
Hello,

I believe this is an issue with the dependencies for picotls, the TLS backend I am using through my own Go bindings. You need the openssl header files to be able to compile picotls. Mine are located in `/usr/lib/include/openssl`.
What system are you running this on ?

**Comment by lohith-bellad** [comment]
Hello,

Thanks for the reply. I am on mac os x Sierra.

**Comment by lohith-bellad** [comment]
Linking openssl headers into my /usr/local/include helped. Thanks,
